// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtcAGcPaSOmM0hu99JKF98-RPm1eGQKGc',
    appId: '1:893255076175:web:99a4b2d610939820711d3a',
    messagingSenderId: '893255076175',
    projectId: 'sesini-duyan-var',
    authDomain: 'sesini-duyan-var.firebaseapp.com',
    storageBucket: 'sesini-duyan-var.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmqaUxF8b8v-Hz4yIv0DkAggD83RRPlGI',
    appId: '1:927189381623:android:1cfb68e632414ad7edbef2',
    messagingSenderId: '927189381623',
    projectId: 'sesini-duyan-var-11c68',
    storageBucket: 'sesini-duyan-var-11c68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBl5l3DN4LBzwz4AyMsdh1fm5xq0p3QuI',
    appId: '1:893255076175:ios:7afff920e20850dc711d3a',
    messagingSenderId: '893255076175',
    projectId: 'sesini-duyan-var',
    storageBucket: 'sesini-duyan-var.firebasestorage.app',
    iosBundleId: 'com.example.sesiniDuyanVar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBl5l3DN4LBzwz4AyMsdh1fm5xq0p3QuI',
    appId: '1:893255076175:ios:7afff920e20850dc711d3a',
    messagingSenderId: '893255076175',
    projectId: 'sesini-duyan-var',
    storageBucket: 'sesini-duyan-var.firebasestorage.app',
    iosBundleId: 'com.example.sesiniDuyanVar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtcAGcPaSOmM0hu99JKF98-RPm1eGQKGc',
    appId: '1:893255076175:web:eda5e460e544c8ea711d3a',
    messagingSenderId: '893255076175',
    projectId: 'sesini-duyan-var',
    authDomain: 'sesini-duyan-var.firebaseapp.com',
    storageBucket: 'sesini-duyan-var.firebasestorage.app',
  );
}